name: Build Nethunter Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip

    - name: Clone Nethunter Project
      run: |
        cd $GITHUB_WORKSPACE
        wget https://github.com/xingqianzhi/alioth_kernel/releases/download/202406232122/dtbo.img
        wget https://github.com/xingqianzhi/alioth_kernel/releases/download/202406232122/Image.gz-dtb
        git clone https://gitlab.com/kalilinux/nethunter/build-scripts/kali-nethunter-project.git
        cd $GITHUB_WORKSPACE/kali-nethunter-project/nethunter-installer
        ./bootstrap.sh
        cd $GITHUB_WORKSPACE/kali-nethunter-project/nethunter-installer/devices/fourteen/alioth-los-ksu/
        rm Image.gz-dtb
        rm dtbo.img
        cd $GITHUB_WORKSPACEkali-nethunter-project/nethunter-installer
        cp -fp $GITHUB_WORKSPACE/Image.gz-dtb devices/fourteen/alioth-los-ksu/
        cp -fp $GITHUB_WORKSPACE/dtbo.img devices/fourteen/alioth-los-ksu/

    - name: Build Nethunter rootfs and kernel install zip
      run: |
        cd $GITHUB_WORKSPACE/kali-nethunter-project/nethunter-installer
        ./build.py -d alioth-los-ksu --rootfs full --fourteen

    - name: Build Nethunter kernel install zip
      run: |
        cd $GITHUB_WORKSPACE/kali-nethunter-project/nethunter-installer
        ./build.py -d alioth-los-ksu --fourteen --kernel

    - name: Upload Kernel Artifact for Nethunter
      uses: actions/upload-artifact@v2
      with:
        name: kernel-nethunter-alioth-los-ksu-fourteen-20240623
        path: kali-nethunter-project/nethunter-installer/kernel-nethunter-*-alioth-los-ksu-fourteen.zip

    - name: Upload Rootfs Artifact for Nethunter
      uses: actions/upload-artifact@v2
      with:
        name: nethunter-alioth-los-ksu-fourteen-kalifs-full-20240623
        path: kali-nethunter-project/nethunter-installer/nethunter-*-alioth-los-ksu-fourteen-kalifs-full.zip
