name: Build Nethunter Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip

    - name: Clone and Build Nethunter Project
      run: |
        cd $GITHUB_WORKSPACE/
        git clone https://gitlab.com/kalilinux/nethunter/build-scripts/kali-nethunter-project.git
        cd $GITHUB_WORKSPACE/kali-nethunter-project/nethunter-installer
        ./bootstrap.sh
        ./build.py -d alioth-los-ksu --rootfs full --fourteen
        ./build.py -d alioth-los-ksu --fourteen --kernel

    - name: Upload kernel artifact
      uses: actions/upload-artifact@v2
      with:
        name: kernel-nethunter
        path: kali-nethunter-project/nethunter-installer/kernel-nethunter-*-alioth-los-ksu-fourteen.zip

    - name: Upload rootfs artifact
      uses: actions/upload-artifact@v2
      with:
        name: rootfs-nethunter
        path: kali-nethunter-project/nethunter-installer/nethunter-*-alioth-los-ksu-fourteen-kalifs-full.zip
